"""Encrata — Email intelligence API for Python."""

from ._version import __version__
from .client import Encrata
from .async_client import AsyncEncrata
from .types import (
    BreachInfo,
    BreachReport,
    CompanyInfo,
    CompanyOfficer,
    CompanyProfile,
    CompanyResult,
    CompanyShareholder,
    ContactList,
    DarkWebResult,
    DarkWebSearch,
    DomainInfo,
    DomainSSL,
    DomainThreatIntel,
    DomainWhois,
    ExtractResult,
    FaceMatch,
    FaceSearch,
    GoogleResult,
    GoogleSearch,
    IPASN,
    IPCompany,
    IPInfo,
    IPLocation,
    IPThreat,
    Monitor,
    MonitorRun,
    MonitorSnapshot,
    NewsArticle,
    Person,
    PhoneBreaches,
    PhoneCarrier,
    PhoneCountry,
    PhoneFormat,
    PhoneInfo,
    PhoneMessaging,
    PhoneRegistration,
    PhoneRisk,
    PhoneValidation,
    Publication,
    RegisteredServices,
    ScrapeResult,
    ScreenshotResult,
    Socials,
    Validation,
)
from .exceptions import (
    APIConnectionError,
    APIError,
    AuthenticationError,
    EncrataError,
    InsufficientCreditsError,
    InvalidRequestError,
    RateLimitError,
)

__all__ = [
    # Client
    "Encrata",
    "AsyncEncrata",
    # Types
    "Person",
    "Socials",
    "BreachInfo",
    "BreachReport",
    "NewsArticle",
    "Publication",
    "RegisteredServices",
    "Validation",
    "Monitor",
    "MonitorRun",
    "MonitorSnapshot",
    "ContactList",
    "IPInfo",
    "IPLocation",
    "IPASN",
    "IPCompany",
    "IPThreat",
    "PhoneInfo",
    "PhoneFormat",
    "PhoneCountry",
    "PhoneCarrier",
    "PhoneMessaging",
    "PhoneValidation",
    "PhoneRegistration",
    "PhoneRisk",
    "PhoneBreaches",
    "DomainInfo",
    "DomainWhois",
    "DomainSSL",
    "DomainThreatIntel",
    "CompanyInfo",
    "CompanyResult",
    "CompanyProfile",
    "CompanyOfficer",
    "CompanyShareholder",
    "GoogleSearch",
    "GoogleResult",
    "DarkWebSearch",
    "DarkWebResult",
    "FaceSearch",
    "FaceMatch",
    "ScrapeResult",
    "ExtractResult",
    "ScreenshotResult",
    # Exceptions
    "EncrataError",
    "AuthenticationError",
    "InsufficientCreditsError",
    "InvalidRequestError",
    "RateLimitError",
    "APIConnectionError",
    "APIError",
    # Metadata
    "__version__",
]
